# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eb2bbddc1bcfecfe939cbee647dd57743a45a64c974dbe6ef1aea66a507f16d239e36f05d7bcd37e886dbd84667f405b50e8ab6f4e59c22ba159eba600e2d08

test:
  secret_key_base: f6e60fb20789c86b3669a930e69e7e499f171db2e1b58050cb1f752e7b2a9277100ff41b84ed0dd6fbc27f08c707244c64c1a609bf6d7fabf3e7ba584fd132d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
